name: STL10
v_target_: climex.data.data_loader.STL10DataModule
#data_dir: ${paths.data_dir}
batch_size: 64 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
train_val_test_split: [4_500, 500, 800]
num_workers: 0
pin_memory: False